// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/asset/asset.proto

package assetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for asset type
type AssetType int32

const (
	AssetType_UNSPECIFIED AssetType = 0
	AssetType_COIN        AssetType = 1
	AssetType_TOKEN       AssetType = 2
	AssetType_FIAT        AssetType = 3
)

// Enum value maps for AssetType.
var (
	AssetType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "COIN",
		2: "TOKEN",
		3: "FIAT",
	}
	AssetType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"COIN":        1,
		"TOKEN":       2,
		"FIAT":        3,
	}
)

func (x AssetType) Enum() *AssetType {
	p := new(AssetType)
	*p = x
	return p
}

func (x AssetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_asset_asset_proto_enumTypes[0].Descriptor()
}

func (AssetType) Type() protoreflect.EnumType {
	return &file_proto_asset_asset_proto_enumTypes[0]
}

func (x AssetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetType.Descriptor instead.
func (AssetType) EnumDescriptor() ([]byte, []int) {
	return file_proto_asset_asset_proto_rawDescGZIP(), []int{0}
}

type CreateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          AssetType              `protobuf:"varint,3,opt,name=type,proto3,enum=asset.AssetType" json:"type,omitempty"`
	Decimals      int32                  `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssetRequest) Reset() {
	*x = CreateAssetRequest{}
	mi := &file_proto_asset_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetRequest) ProtoMessage() {}

func (x *CreateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetRequest.ProtoReflect.Descriptor instead.
func (*CreateAssetRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAssetRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateAssetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAssetRequest) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_UNSPECIFIED
}

func (x *CreateAssetRequest) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *CreateAssetRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssetResponse) Reset() {
	*x = CreateAssetResponse{}
	mi := &file_proto_asset_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetResponse) ProtoMessage() {}

func (x *CreateAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetResponse.ProtoReflect.Descriptor instead.
func (*CreateAssetResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_proto_rawDescGZIP(), []int{1}
}

var File_proto_asset_asset_proto protoreflect.FileDescriptor

const file_proto_asset_asset_proto_rawDesc = "" +
	"\n" +
	"\x17proto/asset/asset.proto\x12\x05asset\"\x9f\x01\n" +
	"\x12CreateAssetRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x04type\x18\x03 \x01(\x0e2\x10.asset.AssetTypeR\x04type\x12\x1a\n" +
	"\bdecimals\x18\x04 \x01(\x05R\bdecimals\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\"\x15\n" +
	"\x13CreateAssetResponse*;\n" +
	"\tAssetType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\b\n" +
	"\x04COIN\x10\x01\x12\t\n" +
	"\x05TOKEN\x10\x02\x12\b\n" +
	"\x04FIAT\x10\x032T\n" +
	"\fAssetService\x12D\n" +
	"\vCreateAsset\x12\x19.asset.CreateAssetRequest\x1a\x1a.asset.CreateAssetResponseBGZEgithub.com/Amir-Sadati/crypto-microservice/crypto-proto/asset;assetpbb\x06proto3"

var (
	file_proto_asset_asset_proto_rawDescOnce sync.Once
	file_proto_asset_asset_proto_rawDescData []byte
)

func file_proto_asset_asset_proto_rawDescGZIP() []byte {
	file_proto_asset_asset_proto_rawDescOnce.Do(func() {
		file_proto_asset_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_asset_asset_proto_rawDesc), len(file_proto_asset_asset_proto_rawDesc)))
	})
	return file_proto_asset_asset_proto_rawDescData
}

var file_proto_asset_asset_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_asset_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_asset_asset_proto_goTypes = []any{
	(AssetType)(0),              // 0: asset.AssetType
	(*CreateAssetRequest)(nil),  // 1: asset.CreateAssetRequest
	(*CreateAssetResponse)(nil), // 2: asset.CreateAssetResponse
}
var file_proto_asset_asset_proto_depIdxs = []int32{
	0, // 0: asset.CreateAssetRequest.type:type_name -> asset.AssetType
	1, // 1: asset.AssetService.CreateAsset:input_type -> asset.CreateAssetRequest
	2, // 2: asset.AssetService.CreateAsset:output_type -> asset.CreateAssetResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_asset_asset_proto_init() }
func file_proto_asset_asset_proto_init() {
	if File_proto_asset_asset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_asset_asset_proto_rawDesc), len(file_proto_asset_asset_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_asset_asset_proto_goTypes,
		DependencyIndexes: file_proto_asset_asset_proto_depIdxs,
		EnumInfos:         file_proto_asset_asset_proto_enumTypes,
		MessageInfos:      file_proto_asset_asset_proto_msgTypes,
	}.Build()
	File_proto_asset_asset_proto = out.File
	file_proto_asset_asset_proto_goTypes = nil
	file_proto_asset_asset_proto_depIdxs = nil
}
