services:
  postgres:
    image: postgres
    environment:
     - POSTGRES_USERNAME=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${POSTGRES_DB}
    container_name: crypto_asset_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pg_asset_data:/var/lib/postgresql/data

volumes:
  pg_asset_data:

